backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: /images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Category-images"
      name: "category-images"
      file: "lib/catGallery.md"
      fields:
        - label: 'Category'
          name: "category"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Image", name: "thumbnail", widget: "image"}

